<form action="zahlungbearbeiten" method="post">

<table>
<th>Zahlung bearbeiten</th>
<tr><td>Zahlungsbeschreibung: </td><td><input name="zahlungsbeschreibung" type="text" maxlength="50" size="20" value="<?=$zahlung[0]->getZahlungsbeschreibung()?>" required></td></tr>
<tr><td>Betrag: </td><td><input name="betrag" type="text" maxlength="50" size="20" value="<?=$zahlung[0]->getBetrag()?>" required></td></tr>
<tr><td>Zahlungsdatum: </td><td><input type="date" name="zahlungsdatum" value="<?=$zahlung[0]->getZahlungsdatum()?>" placeholder="YYYY-MM-DD" required></td></tr>
<tr><td>Kategorie: </td><td>
	<select name="kategorie" size="5">
	<?php
	/**
	//Alle Kategorien in die Auswahlliste schreiben
	foreach ($kategorieListe as $zaehler => $kategorie) { ?>
			<option value='<?=$kategorie->getK_id()?>'> <?=$kategorie->getKategoriebeschreibung() ?> </option>
	<?php } 
	*/
	?> 
	</select>
</td></tr>
<tr><td>Teilnehmer: </td>

	<td><fieldset>
		<?php 
		/**
		//Alle Gruppenmitglieder in die Auswahlliste schreiben
		foreach ($mitgliederListe as $zaehler => $mitglied) { ?>	
			<label>
			<input type="checkbox" name="zahlungsteilnehmer[]" value='<?=$mitglied->getU_id()?>'>
			<?=$mitglied->getUsername()?>
			<br>Anteil: <input type="text" name="anteilsbetrag[]" placeholder="Euro.Cent">
			</label><br>	
			 			
		<?php 
		}
		*/
		?> 
	</fieldset></td>

</tr>


										
<input type="hidden" name="z_id" value='<?=$zahlung[0]->getZ_id()?>'>
<input type="hidden" name="g_id" value='<?=$gruppe[0]->getG_id()?>'>																		
<tr><td><input type="submit" name="speichern" value="Zahlung bearbeiten"></td> </tr>

</table>
</form>
	
	
	
