<?=$msg?>

<h3><?=$user[0]->getUsername()?>'s Profil</h3>

	<table>	
		<tr><th></th><th></th><th><th></tr>
		<tr><td width="50">Name</td><td><?=$user[0]->getVorname()?> <?=$user[0]->getNachname()?></td><td rowspan=2 width="300" align="center"><img src =<?=$user[0]->getTeilnehmerbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></td></tr>
		<tr><td width="50">E-Mail</td><td><?=$user[0]->getEmail()?></td></tr>
		<tr><td></td><td></td><td width="300" align="center">	<form enctype="multipart/form-data" method="POST">
									<input type="file" name="uploadedfile" />
        							<input type="hidden" name="u_id" readonly="readonly" value="<?=!is_null ($user[0]->getU_id()) ? $user[0]->getU_id():"<automatisch>"?>">
        							<input type="submit" name="profilbild" value="Bild bearbeiten">
   									 </form> </td></tr>
	</table>
 