<?=$msg?>

<h3><?=$user[0]->getUsername()?>'s Profil</h3>

	<table>	
		<tr><th></th><th></th><th><th></tr>
		<tr><td width="50">Name</td><td><?=$user[0]->getVorname()?> <?=$user[0]->getNachname()?></td><td rowspan=2 width="300" align="right"><img src =<?=$user[0]->getTeilnehmerbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></td></tr>
		<tr><td width="50">E-Mail</td><td><?=$user[0]->getEmail()?></td></tr>	
	</table>
