<?=$msg?>

<h3><?=$user[0]->getUsername()?>'s Profil</h3>

	<table class="profil" >	
		<tr><td width="50"><i>Name: </i></td></tr>
		<tr><td><?=$user[0]->getVorname()?> <?=$user[0]->getNachname()?></td><td rowspan="4" width="200" align="right"><div class="big-circular-image"><img src =<?=$user[0]->getTeilnehmerbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></div></td></tr>
		<tr><td width="50"><i>E-Mail: </i></td></tr>
		<tr><td><?=$user[0]->getEmail()?></td></tr>
		
		
		<tr><td></td></tr>
		<tr><td colspan="3" width="300" align="right">	<form enctype="multipart/form-data" method="POST">
									<input type="file" name="uploadedfile" />
        							<input type="hidden" name="u_id" readonly="readonly" value="<?=!is_null ($user[0]->getU_id()) ? $user[0]->getU_id():"<automatisch>"?>">
        							<input class="button" type="submit" name="profilbild" value="Bild bearbeiten">
   									 </form> </td></tr>
   		 
	
 			<form method="post" action="passwordreset">
<tr><td style="colspan:3; align:center" ><input class="button" style="background-color:#e8e8e8; color:#96b296" type="submit" name="passwortzuruecksetzen" value="Passwort zur&uuml;cksetzen"></td></tr>
</form>	

</table>	