<h1>Passwort vergessen</h1>

<?=$msg?>
<br>

<div class="container">

<form method='post'>

<div class="form-group" style="width:300px">
    <label for="email">E-Mail:</label>

<input type="email" class="form-control" id="email" name="email"placeholder="E-Mail" required>
</div>

<br>

<input class="button" type="submit" name="emailpasswort" value="E-Mail anfordern">

</form>

</div>
