<h1>Passwort vergessen</h1>
<br>

<div class="container">

<form method='post'>

<div class="form-group" style="width:300px">
	<label>Neues Passwort: </label>
	<input class="form-control" type="password" name="passwort" required>
</div>

<div class="form-group" style="width:300px">
	<label>Neues Passwort wiederholen:</label>
	<input class="form-control" type="password" name="passwortwdh" required>
</div>

<br>

<input class="button" type="submit" name="passwortvergessen" value="Passwort zur&uuml;cksetzen">

</form>
</div>
