<h1>Passwort vergessen</h1>
<br><br>

<div class="container">

<form method='post'>

<table>

<tr><td>E-Mail:</td><td> <input type="email" name="email" required></td></tr>
<tr><td>Neues Passwort:</td><td> <input type="password" name="passwort" required></td></tr>
<tr><td>Neues Passwort wiederholen:</td><td> <input type="password" name="passwortwdh" required></td></tr>

</table>

<br><br>

<input type="submit" name="passwortvergessen" value="Passwort zur&uuml;cksetzen">

</form>
</div>
