<?=$msg?>

<h1>Benutzerliste</h1>
<center>

<thead>
<tr>

<th> User-ID 		</th>
<th> Benutzername 	</th>
<th> Vorname 		</th>
<th> Nachname 		</th>
<th> Passwort		</th>
<th> E-Mail			</th>
<th> Deaktiviert 	</th>
<th> Systemadmin 	</th>

</tr>
<?php 
	foreach ($userListe as $zaehler => $user) {
	?>
<tr>
			<td>	<?=$user->getU_id()?>			</td>
			<td>	<?=$user->getUsername()?>		</td>
			<td>	<?=$user->getVorname()?>		</td>
			<td>	<?=$user->getNachname()?>		</td>
			<td>	<?=$user->getPasswort()?>		</td>
			<td>	<?=$user->getEmail()?>			</td>
			<td>	<?=$user->getDeaktiviert()?>	</td>
			<td>	<?=$user->getSystemadmin()?>	</td> 

<?php
}
?>
</tr>

</thead>
</table>
</center>