
<?php 

// output headers so that the file is downloaded rather than displayed
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=data.csv');

// create a file pointer connected to the output stream
$output = fopen('php://output', 'w');

// output the column headings
fputcsv($output, array('Betrag'));
		//, 'Column 2', 'Column 3'));



// loop over the rows, outputting them
//while ($row = mysql_fetch_assoc($rows)) fputcsv($output, $row);

foreach($zahlungsliste as $zahlung){
	$betrag = $zahlung->getBetrag();
	//echo $betrag;
	fputcsv($output, $betrag);
}


?>

<h1>CSV-Ausgabe</h1>




