<h1>FAQ </h1>
 <br>
 <b>Frage: </b>
 <br>Was ist Grouppay?
 <br><br>
 <b>Antwort: </b>
 <br>Grouppay ist eine Zahlungsverwaltung-App f&uumlr Gruppen, mehr Informationen gibt es auf der <a href="<?= $this->url('application') ?>">Startseite</a>.
 <br><br><br><br>
 
 <b>Frage: </b>
 <br>Kann ich über die App nur meine Ausgaben verwalten?
 <br><br>
 <b>Antwort: </b>
 <br>Grouppay wurde f&uumlr Gruppen entwickelt. Um Zahlungen anlegen zu k&oumlnnen muss man Mitglied einer Gruppe sein. Eine Gruppe besteht aus mindestens zwei Personen.
 <br><br><br><br>
 
 <b>Frage: </b>
 <br>Wie kann ich Zahlungen anlegen?
 <br><br>
 <b>Antwort: </b>
 <br>Eine Zahlung kann angelegt werden, sobald man sich eine Gruppe anzeigen l&aumlsst. In diesem Fall erscheint im Men&uuml der Punkt "Zahlung anlegen".
 <br><br<br><br>
 
 <b>Frage: </b>
 <br>Ich weiß mein Passwort nicht mehr, was nun?
 <br><br>
 <b>Antwort: </b>
 <br>In dem Fall, dass das Passwort vergessen wurde, kann bei der Anmeldung der entspechende Link verwendet werden.
 <br><br><br><br>
 
 <b>Frage: </b>
 <br>Ich wurde deaktiviert, warum?
 <br><br>
 <b>Antwort: </b>
 <br>User werden von einem Admin deaktiviert, falls sie unter anderem unangemessene W&oumlrter verwenden. Sollte die Deaktivierung unrechtm&aumlßig erfolgt sein, kann der Admin verst&aumlndigt werden.
 <br><br><br><br>