<?php session_start();?>
<h1>FAQ </h1>

<ul class="list-group">
 <li class="list-group-item" style="background-color: #fcfffc">
 <b>Frage: </b>
 <br>Was ist Grouppay?
 <br>
 <b>Antwort: </b>
 <br>Grouppay ist eine Zahlungsverwaltung-App f&uuml;r Gruppen, mehr Informationen gibt es auf der
 	<?php if ($_SESSION['angemeldet']=='ja' || $_SESSION['systemadmin']=="ja") {?>
 				Startseite.
 	<?php }
 	else {?>			
 				<a href="<?= $this->url('application') ?>" style="color:#96b296">Startseite</a>.
 	<?php }?>
 <br>
 </li>
 
 <li class="list-group-item" style="background-color: #dae7da">
 <b>Frage: </b>
 <br>Kann ich &uuml;ber die App nur meine Ausgaben verwalten?
 <br>
 <b>Antwort: </b>
 <br>Grouppay wurde f&uuml;r Gruppen entwickelt. Um Zahlungen anlegen zu k&ouml;nnen muss man Mitglied einer Gruppe sein.
 <br>
 </li>
 
 <li class="list-group-item" style="background-color: #fcfffc">
 <b>Frage: </b>
 <br>Wie kann ich Zahlungen anlegen?
 <br>
 <b>Antwort: </b>
 <br>Eine Zahlung kann angelegt werden, sobald man sich eine Gruppe anzeigen l&auml;sst. Hier befindet sich der Button "Neue Zahlung anlegen".
 <br>
 </li>
 
 <li class="list-group-item" style="background-color: #dae7da">
  <b>Frage: </b>
 <br>Wie kann ich eine Nachricht l&ouml;schen?
 <br>
 <b>Antwort: </b>
 <br>Nachrichten k&ouml;nnen nur von ihrem Verfasser gel&ouml;scht werden. Dem Verfasser wird im Message Board hinter der Nachricht ein Icon angezeigt. Dieses leitet ihn auf eine Seite, auf der er die Nachricht bearbeiten oder entfernen kann.
 <br>
 </li>
 
 <li class="list-group-item" style="background-color: #fcfffc">
 <b>Frage: </b>
 <br>Ich wei&szlig; mein Passwort nicht mehr, was nun?
 <br>
 <b>Antwort: </b>
 <br>In dem Fall, dass das Passwort vergessen wurde, kann bei der Anmeldung der entspechende Link verwendet werden.
 <br>
 </li>
 
 <li class="list-group-item" style="background-color: #dae7da">
 <b>Frage: </b>
 <br>Ich wurde deaktiviert, warum?
 <br>
 <b>Antwort: </b>
 <br>User werden von einem Admin deaktiviert, falls sie unter anderem unangemessene W&ouml;rter verwenden. Sollte die Deaktivierung unrechtm&auml;&szlig;ig erfolgt sein, kann ein Admin verst&auml;ndigt werden.
 <br>Kontakt zu unserem Systemadmin: <span class="glyphicon glyphicon-envelope"></span> <a class="mail"  href="mailto:buchba10gw.uni-passau.de" title="&Ouml;ffnet ein neues Fenster um eine E-Mail zu versenden" style="color:#96b296">Matthias Buchbauer </a> (buchba10@gw.uni-passau.de)
 <br>
 </li>
 </ul>