<?php session_start();?>
<h1>FAQ </h1>
 <br>
 <b>Frage: </b>
 <br>Was ist Grouppay?
 <br>
 <b>Antwort: </b>
 <br>Grouppay ist eine Zahlungsverwaltung-App f&uumlr Gruppen, mehr Informationen gibt es auf der
 	<?php if ($_SESSION['angemeldet']=='ja' || $_SESSION['systemadmin']=="ja") {?>
 				Startseite.
 	<?php }
 	else {?>			
 				<a href="<?= $this->url('application') ?>">Startseite</a>.
 	<?php }?>
 <br><br><br>
 
 <b>Frage: </b>
 <br>Kann ich &uumlber die App nur meine Ausgaben verwalten?
 <br>
 <b>Antwort: </b>
 <br>Grouppay wurde f&uumlr Gruppen entwickelt. Um Zahlungen anlegen zu k&oumlnnen muss man Mitglied einer Gruppe sein.
 <br><br><br>
 
 <b>Frage: </b>
 <br>Wie kann ich Zahlungen anlegen?
 <br>
 <b>Antwort: </b>
 <br>Eine Zahlung kann angelegt werden, sobald man sich eine Gruppe anzeigen l&aumlsst. In diesem Fall erscheint im Men&uuml der Punkt "Zahlung anlegen".
 <br><br><br>
 
  <b>Frage: </b>
 <br>Wie kann ich eine Nachricht l&oumlschen?
 <br>
 <b>Antwort: </b>
 <br>Nachrichten können nur von ihrem Verfasser gel&oumlscht werden. Dem Verfasser wird im Message Board hinter der Nachricht ein Icon angezeigt. Dieses leitet ihn auf eine Seite, auf der er die Nachricht bearbeiten oder entfernen kann.
 <br><br><br>
 
 <b>Frage: </b>
 <br>Ich wei&szlig mein Passwort nicht mehr, was nun?
 <br>
 <b>Antwort: </b>
 <br>In dem Fall, dass das Passwort vergessen wurde, kann bei der Anmeldung der entspechende Link verwendet werden.
 <br><br><br>
 
 <b>Frage: </b>
 <br>Ich wurde deaktiviert, warum?
 <br>
 <b>Antwort: </b>
 <br>User werden von einem Admin deaktiviert, falls sie unter anderem unangemessene W&oumlrter verwenden. Sollte die Deaktivierung unrechtm&auml&szligig erfolgt sein, kann ein Admin verst&aumlndigt werden.
 <br><br><br>