<?php session_start();?>
<h1>Nachricht bearbeiten</h1>

<form  method='post'>
    <label>Nachricht:</label><br>
    <textarea name="text" required rows="5" cols="40" ><?=$nachricht[0]->getText()?></textarea>
    <br>
    <input class="button" type="submit"  name = "bearbeiten" value="Bearbeiten"><input class="button" type="submit"  name = "loeschen" value="L&ouml;schen">
    <a class ="button"  href = http://132.231.36.206/groupshow?g_id=187> Zur&uuml;ck</a>
</form>