<head>
<style>
.button{
    font-size: 1.5rem;
}
</style>
</head>         

<form method='post'>
	
	<input type='hidden' name='z_id' value='<?=$Zahlung->getZ_id()?>'>
		
	Soll die Zahlung <?=$Zahlung->getZ_id()?> wirklich gel&oumlscht werden?
		
	<input class='button' type='submit' name='send' value='Ja'>
	<input class='button' type='submit' name='abbrechen' value='Nein'>
		
</form>