<h1>Registrierung</h1>
<br>
<?=$msg?>
<br>


<form method='post'>

<div class="form-group" style="width:300px">
<label>Benutzername:</label> <input type="text" class="form-control" name="username" required>
</div>

<div class="form-group" style="width:300px">
<label>Passwort:</label> <input type="password"  class="form-control" name="passwort" required>
</div>

<div class="form-group" style="width:300px">
<label>Passwort wiederholen:</label> <input type="password" class="form-control" name="passwortwdh" required>
</div>

<div class="form-group" style="width:300px">
<label>E-Mail:</label> <input type="email" name="email" class="form-control" required>
</div>

<div class="form-group" style="width:300px">
<label>Vorname:</label> <input type="text" class="form-control" name="vorname" required>
</div>

<div class="form-group" style="width:300px">
<label>Nachname:</label> <input type="text" class="form-control" name="nachname" required>
</div>

<input type="hidden" value = 0 name="ist_admin">

<br><br>
<input class="button" type = "submit" name ="registrieren" value = "Jetzt Registrieren">
</form>