<h1>Registrierung</h1>
<br>
<?=$msg?>
<br>


<form method='post'>

<table>
<div class="form-group" style="width:300px">
<tr><td>Benutzername:</td><td> <input type="text" class="form-control" name="username" required></td></tr>
</div>

<div class="form-group" style="width:300px">
<tr><td>Passwort:</td><td> <input type="password"  class="form-control" name="passwort" required></td></tr>
</div>

<div class="form-group" style="width:300px">
<tr><td>Passwort wiederholen:</td><td> <input type="password" class="form-control" name="passwortwdh" required></td></tr>
</div>

<div class="form-group" style="width:300px">
<tr><td>E-Mail:</td><td> <input type="email" name="email" class="form-control" required></td></tr>
</div>

<div class="form-group" style="width:300px">
<tr><td>Vorname:</td><td> <input type="text" class="form-control" name="vorname" required> </td></tr>
</div>

<div class="form-group" style="width:300px">
<tr><td>Nachname:</td><td> <input type="text" class="form-control" name="nachname" required></td></tr>
</div>

<input type="hidden" value = 0 name="ist_admin">

</table>

<br><br>
<input class="button" type = "submit" name ="registrieren" value = "Jetzt Registrieren">
</form>