<h1>Registrierung</h1>
<br>
<?=$msg?>
<br>


<form method='post'>

<table>
<tr><td>Benutzername:</td><td> <input type="text" name="username" required></td></tr>
<tr><td>Passwort:</td><td> <input type="password" name="passwort" required></td></tr>
<tr><td>Passwort wiederholen:</td><td> <input type="password" name="passwortwdh" required></td></tr>
<tr><td>E-Mail:</td><td> <input type="email" name="email" required></td></tr>
<tr><td>Vorname:</td><td> <input type="text" name="vorname" required> </td></tr>
<tr><td>Nachname:</td><td> <input type="text" name="nachname" required></td></tr>

<input type="hidden" value = 0 name="ist_admin">

</table>

<br><br>
<input class="button" type = "submit" name ="registrieren" value = "Jetzt Registrieren">
</form>