<?=$msg?>


<h1>Neues Mitglied zu Grouppay einladen:</h1>

<form method="post">
<table>
	<tr><td>E-Mail:</td><td><input name="email" type="text" value="<?=$email?>" maxlength="255" size="20" required></td></tr>
	<tr><td><input class="button" type="submit" name="einladen" value="Einladen"></td> </tr> 
</table>
	<div>(Achtung: Es können nur an uni-interne Mailadressen Einladungen verschickt werden)</div> 
</form>


