<?=$msg?>
<?=$maileingabpruefung?>


<h1>Neues Mitglied zu Grouppay einladen:</h1>

<center>
<form method="post">
<div class="form-group" style="width:300px">
	<table>
	<tr><td><label>E-Mail:</label></td></tr>
	<tr><td><input name="email" type="text" class="form-control" style="text-align:left" value="<?=$email?>" maxlength="255" size="30" required></td></tr>
	</table>
	<input class="button" type="submit" name="einladen" value="Einladen">
</div>
	<div>(Achtung: Es können nur an uni-interne <br> Mailadressen Einladungen verschickt werden)</div> 
</form>

</center>
