<?=$msg?>
<?php session_start();
?>
<h3><?=$user[0]->getUsername()?>'s Profil</h3>

	<table>	
		<tr><th></th><th></th><th><th></tr>
		<tr><td width="100"><i>Name:</i></td><td><?=$user[0]->getVorname()?> <?=$user[0]->getNachname()?></td><td rowspan=2 width="300" align="center"><div class="big-circular-image"><img src =<?=$user[0]->getTeilnehmerbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></div></td></tr>
		<tr><td width="100"><i>Benutzername:</i></td><td><?=$user[0]->getUsername()?></td></tr>
		<tr><td width="100"><i>E-Mail:</i></td><td><?=$user[0]->getEmail()?></td></tr>
	</table>
	
<br><br>
<h4>Schulden von mir an <?=$user[0]->getUsername()?> (gruppenunabh&auml;ngig):</h4>
<form action="fremdesprofil?u_id=<?=$_REQUEST['u_id']?>" method="post">

<div class="form-group" style="width:300px">
	<label>Schulden pflegen</label>
</div>

<div class="form-group" style="width:300px">
	<label>Offene Schulden: </label>
	<input class="form-control" name="offen_an_aufgerufenen" type="text" maxlength="50" style="width: 13em;" value="<?=$schulden_an_aufgerufenen[0]?>" required readonly>
</div>

<div class="form-group" style="width:300px">
<label>Begleichen: </label>
<input class="form-control" name="begleichen_an_aufgerufenen" type="number" step=".01" maxlength="50" style="width: 13em;" placeholder="Euro.Cent" required min="0" max="<?=$schulden_an_aufgerufenen[0]?>">										
</div>

<input class="button" type="submit" name="speichern_an_aufgerufenen" value="Betrag als bezahlt speichern">
 
</form>  
 

<br><br> 


<h4>Schulden von <?=$user[0]->getUsername()?> an mich (gruppenunabh&auml;ngig):</h4>
<form action="fremdesprofil?u_id=<?=$_REQUEST['u_id']?>" method="post">

<div class="form-group" style="width:300px">
<label>Schulden pflegen</label>
</div>

<div class="form-group" style="width:300px">
	<label>Offene Schulden: </label>
	<input class="form-control" name="offen_an_angemeldeten" type="text" maxlength="50" style="width: 13em;" value="<?=$schulden_an_angemeldeten[0]?>" required readonly>
</div>

<div class="form-group" style="width:300px">
	<label>Begleichen: </label>
	<input class="form-control" name="begleichen_an_angemeldeten" type="number" step=".01" maxlength="50" style="width: 13em;" placeholder="Euro.Cent" min="0" max="<?=$schulden_an_angemeldeten[0]?>" required>									
</div>

<input class="button" type="submit" name="speichern_an_angemeldeten" value="Betrag als bezahlt speichern">

</form>




