<?=$msg?>

<h3><?=$user[0]->getUsername()?>'s Profil</h3>

	<table>	
		<tr><th></th><th></th><th><th></tr>
		<tr><td width="100"><i>Name:</i></td><td><?=$user[0]->getVorname()?> <?=$user[0]->getNachname()?></td><td rowspan=2 width="300" align="center"><div class="big-circular-image"><img src =<?=$user[0]->getTeilnehmerbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></div></td></tr>
		<tr><td width="100"><i>Benutzername:</i></td><td><?=$user[0]->getUsername()?></td></tr>
		<tr><td width="100"><i>E-Mail:</i></td><td><?=$user[0]->getEmail()?></td></tr>
	</table>
	
<br><br>
<h4>Schulden an <?=$user[0]->getUsername()?>:</h4>
<br><br>
<h4>Schulden von <?=$user[0]->getUsername()?>:</h4>