<?php session_start();
use Application\Model\Gruppenmitglied;?>
<?=$msg?>
<?=$err?>


<table class="datentabelle">
<thead class="datentabelle">
	<tr class="datentabelle">
		<th class="datentabelle">Gruppenbild</th>
		<th class="datentabelle">GruppenNr</th>
		<th class="datentabelle">Gruppenname</th>
		<th class="datentabelle">Beschreibung</th>
		<th class="datentabelle"></th>
		<th class="datentabelle"></th>
		<th class="datentabelle"></th>
	</tr>
</thead>

<tbody class="datentabelle">
	<?php 
	foreach ($gruppenListe as $zaehler => $gruppenmitglied) {
		
	?>

		<tr class="datentabelle">
			<td class="datentabelle"><div class="small-circular-image"><img src ="<?=$gruppenmitglied->getGruppe()->getGruppenbildpfad()?>" height = "50" width = "50" alt = "Kein Bild vorhanden"></div></td>
			<td class="datentabelle"><?=$gruppenmitglied->getGruppe()->getG_id()?></td>
			<td class="datentabelle"><?=$gruppenmitglied->getGruppe()->getGruppenname()?></td>
			<td class="datentabelle"><?=$gruppenmitglied->getGruppe()->getGruppenbeschreibung()?></td>
			
			<td><a href='groupshow?g_id=<?=$gruppenmitglied->getGruppe()->getG_id()?>'><img src="img/show.jpg" title="Gruppendetails anzeigen"/></a></td>
			<?php //Nicht schön programmiert
			if ($gruppenmitglied->getGruppenadmin()=="1") {
			?>
				<td><a href='groupedit?g_id=<?=$gruppenmitglied->getGruppe()->getG_id()?>'><img src="img/edit.jpg" title="Gruppendetails bearbeiten"/></a></td>
				<td><a href='groupdelete?g_id=<?=$gruppenmitglied->getGruppe()->getG_id()?>'><img src="img/delete.png" title="Gruppe l&ouml;schen"/></a></td>
			<?php }
			?>
			
		</tr>

	<?php 
		
	}
	?>
		<tr><td> </td></tr>
		<tr>
		<td class="datentabelle"><a href='gruppeanlegen'>Neue Gruppe anlegen</a></td>
		</tr>
</tbody>
</table>	
