<?php session_start();
use Application\Model\Gruppenmitglied;?>
<?=$msg?>
<?=$err?>

<!-- 
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<div class="container">
<div class="table-responsive">
 -->

<br>
<a class="button" href='gruppeanlegen'>Neue Gruppe anlegen</a>
<br><br><br>
<!-- 
<table class="datenuntereinander datentabelle" style="border-collapse: separate; border-spacing: 15px">
 -->


<table class="datenuntereinander datentabelle" style=width:100%>
<thead class="datenuntereinander datentabelle">
	<tr class="datenuntereinander datentabelle">
		<th class="datenuntereinander datentabelle">Gruppenbild</th>
		<th class="datenuntereinander datentabelle">Gruppenname</th>
		<th class="datenuntereinander datentabelle">Beschreibung</th>
		<th class="datenuntereinander datentabelle"></th>
		<th class="datenuntereinander datentabelle"></th>
		<th class="datenuntereinander datentabelle"></th>
	</tr>
</thead>

<tbody class="datenuntereinander datentabelle" >
	<?php 
	foreach ($gruppenListe as $zaehler => $gruppenmitglied) {
		
	?>

		<tr class="datenuntereinander datentabelle">
			<td class="datenuntereinander datentabelle" ><div class="small-circular-image"><img src ="<?=$gruppenmitglied->getGruppe()->getGruppenbildpfad()?>" height = "50" width = "50" alt = "Kein Bild vorhanden"></div></td>
			<td class="datenuntereinander datentabelle" data-label="Gruppenname"><?=$gruppenmitglied->getGruppe()->getGruppenname()?></td>
			<td class="datenuntereinander datentabelle" data-label="Gruppenbeschreibung"><?=$gruppenmitglied->getGruppe()->getGruppenbeschreibung()?></td>
			
			<td class="datentabelle" data-label="Gruppenname"><a href='groupshow?g_id=<?=$gruppenmitglied->getGruppe()->getG_id()?>'><img src="img/show.jpg" title="Gruppendetails anzeigen"/></a></td>
			<?php 
			if ($gruppenmitglied->getGruppenadmin()=="1") {
			?>
				<td class="datentabelle"><a href='groupedit?g_id=<?=$gruppenmitglied->getGruppe()->getG_id()?>'><img src="img/edit.jpg" title="Gruppendetails bearbeiten"/></a></td>
				<td class="datentabelle"><a href='groupdelete?g_id=<?=$gruppenmitglied->getGruppe()->getG_id()?>'><img src="img/delete.png" title="Gruppe l&ouml;schen"/></a></td>
			<?php } else { ?>
				<td class="datentabelle"></td>
				<td class="datentabelle"></td>
			<?php }
			?>
			
		</tr>

	<?php 
		
	}
	?>
</tbody>		

</table>	

<!--  
</div>
</div>
-->
