<?=$msg?>

<?php 
use Application\Model\Gruppenmitglied;
use Application\Model\Kategorie;
?>

<h1>Gruppen&uumlbersicht</h1>

<div class=>
<table>
<tr><td>Gruppenname: <?=$gruppe[0]->getGruppenname()?></td><td rowspan=2 width="300" align="right"><img src =<?=$gruppe[0]->getGruppenbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></td></tr>
<tr><td>Beschreibung: <?=$gruppe[0]->getGruppenbeschreibung()?></td></tr>
</table>
</div>


<div>Hierhin kommt das interne Message-Board einer Gruppe </div>


<table>
	<tr><th>Gruppenmitglieder:</th></tr>
	<tr>
		<th></th>
		<th>Vorname</th>
		<th>Nachname</th>
		<th>Benutzername</th>
		<th>Gruppenadmin</th>
		<th></th>
	</tr>
	
	<?php 
	foreach ($mitgliederListe as $zaehler => $mitglied) {
	?>

		<tr>
			<td><img src ="img/anonymeruser.png" height = "50" width = "50" alt = "Kein Bild vorhanden"></td>
			<td><?=$mitglied->getVorname()?></td>
			<td><?=$mitglied->getNachname()?></td>
			<td><?=$mitglied->getUsername()?></td>
		
			
			<?php 
				foreach ($mitgliedschaft as $counter => $infos) {
				 if ($mitglied->getU_id() == $infos->getU_id() ) {
					
					if ($infos->getGruppenadmin()=="1") { 
					?>
					<td>ja</td>
					<?php 	} else {
					?>
					<td>nein</td>
			<?php 
					}
				 }		
				}
			?> 
		</tr>

	<?php 
	}
	?>
	</table>
	<br>
	<br> 
	
	
	<form action="usersuchen" method="post">

	<table>
		<tr><td>Suche:</td><td><input name="suche" type="text" maxlength="255" size="20" required></td>
		 <input type="hidden" name="g_id" readonly="readonly" value="<?=$gruppe[0]->getG_id()?>">
		<td><input type="submit" value="User suchen"></td> </tr>
	</table>
	</form>
	
		<form action="usersuchen" method="post">
		
		<br>
		<br>

	<table>
		<tr><td>Zahlungsbeschreibung: </td><td><input name="zahlungsbeschreibung" type="text" maxlength="50" size="20" required></td></tr>
		<tr><td>Betrag: </td><td><input name="betrag" type="text" maxlength="50" size="20" required></td></tr>
		<tr><td>Zahlungsdatum: </td><td><input name="zahlungsdatum" type="date" required></td></tr>
		<tr><td>Kategorie: </td><td><select name="kategorie" size="3" required>
											<option>test</option>
										 <?php 
										//Alle Kategorien in die Auswahlliste schreiben
										foreach ($kategorieListe as $zaehler => $kategorie) { ?>
											<option> <? $kategorie->getKategoriebeschreibung() ?></option>
										
										
										<?php } ?> 
										</select></td></tr>
										
																			
		<tr><td><input type="submit" value="Zahlung anlegen"></td> </tr>
	</table>
	</form>
	
	<br>
	<br>
	
	
	<form>
  <label>Künstler(innen):
    <select name="top5" size="5" multiple>
      <option>Heino</option>
      <option>Michael Jackson</option>
      <option>Tom Waits</option>
      <option>Nina Hagen</option>
      <option>Marianne Rosenberg</option>
    </select>
  </label>
</form>




<?php 
										//Alle Kategorien in die Auswahlliste schreiben
										foreach ($kategorieListe as $zaehler => $kategorie) {
											echo 'sepp';
										}
										?>
										