<?=$msg?>

<h1>Gruppen&uumlbersicht</h1>

<div class=>
<table>
<tr><td>Gruppenname: <?=$gruppe[0]->getGruppenname()?></td><td rowspan=2 width="300" align="right"><div class="big-circular-image"><img src =<?=$gruppe[0]->getGruppenbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></div></td></tr>
<tr><td>Beschreibung: <?=$gruppe[0]->getGruppenbeschreibung()?></td></tr>
</table>
</div>



<br><br><br>

<form action="gruppenverlauf?g_id=<?=$_REQUEST['g_id']?>" method="post">
		<table>
		<td><input type="hidden" name='g_id' value=<?=$_REQUEST['g_id']?></td> </tr>
		<td><input type="submit" value="Gruppenverlauf"></td> </tr>
		</table>
	</form>	


<br><br>



<form  method='post'>
    <label>Nachricht:</label><br>
    <textarea name="text" rows="5" cols="40"> </textarea>
    <br>
    <input type="submit"  name = "abschicken" value="Abschicken">
</form>




<br><br><br>


<table>
	<tr><th>Gruppenmitglieder:</th></tr>
	<tr>
		<th></th>
		<th>Vorname</th>
		<th>Nachname</th>
		<th>Benutzername</th>
		<th>Gruppenadmin</th>
		<th></th>
	</tr>
	
	
	<?php 
	foreach ($mitgliederListe as $zaehler => $gruppenmitglied) {
	?>

		<tr>
			<td><div class="small-circular-image"><img src =<?=$gruppenmitglied->getUser()->getTeilnehmerbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></div></td>
			<td><?=$gruppenmitglied->getUser()->getVorname()?></td>
			<td><?=$gruppenmitglied->getUser()->getNachname()?></td>
			<td><?=$gruppenmitglied->getUser()->getUsername()?></td>
			<?php
			if ($gruppenmitglied->getGruppenadmin() == "1") {
				?>
					<td>ja</td>
			<?php } else {
				?>
					<td>nein</td>
			<?php 
				}		
			?>
			<input type="hidden" name="gruppenadminwert" value="<?=$gruppenmitglied->getGruppenadmin()?>">
			<td><input type="submit" name="gruppenadmin" value="Gruppenadminrechte &auml;ndern"><img src="img/add.jpg" /></td>
		</tr>

	<?php 
	}
	?>
	</table>
	<br>
	<br> 
		<form action="groupcsv" method="post">
		<table>
		<th>Download aller Zahlungen dieser Gruppe als CSV</th></tr>
		<td><input type="hidden" name='g_id' value=<?=$_REQUEST['g_id']?></td> </tr>
		<td><input type="submit" value="CSV Download"></td> </tr>
		
	</table>
	</form>	
	
	<br>
	<br>
	
	
	<form action="usersuchen" method="post">

	<table>
		<th>Neues Mitglied hinzuf&uuml;gen</th>
		<tr><td>Suche:</td><td><input name="suche" type="text" maxlength="255" size="20" required></td>
		 <input type="hidden" name="g_id" readonly="readonly" value="<?=$gruppe[0]->getG_id()?>">
		<td><input type="submit" value="User suchen"></td> </tr>
	</table>
	</form>
	
	
	
	




										