 <h1>Overview</span></h1>
 
<?php
	session_start();
	if($_SESSION['angemeldet'] == 'ja'){
		echo $_REQUEST['message'];
	?>

<div class=>Hallo <?=$user[0]->getVorname();?>! Sie wurden erfolgreich eingeloggt.</div>
<br>
<br>
<a onclick="text1.style.display='none';an.style.display='block1';zu.style.display='none'" id="zu" style="display: block1" href="#neu1"><img src="img/X.jpg" /></a>
<a onclick="text1.style.display='block1';an.style.display='none';zu.style.display='block1'" id="an" style="display: none" href="#neu1"></a>
<a name="neu1"></a>
<DIV id="text1" style="display: block1">
<h4>In den letzten f&uumlnf Tagen wurden in Ihren Gruppen folgende Zahlungen erstellt:</h4>

<table width="80%">
  <tr>
    <th width="12%">Gruppe</th>
    <th>Zahlungsbeschreibung</th>
    <th>Zahlungsdatum</th>
    <th width="5%">Betrag</th>
    <th width="12%">Kategorie</th>
    <th>Erstellungsdatum</th>
  </tr>
  
	<?php foreach ($aktzahlung as $zaehler => $zahlung) {?>

  <tr>
    <td><?=$zahlung->getGruppe()->getGruppenname()?></td>
    <td><?=$zahlung->getZahlungsbeschreibung()?></td>
    <td><?=$zahlung->getZahlungsdatum()?></td>
    <td align="right"><?=$zahlung->getBetrag()?></td>
    <td align="center"><?=$zahlung->getKategorie()->getKategoriebeschreibung()?></td>
    <td><?=$zahlung->getErstellungsdatum()?></td>
  </tr>
  <?php }?>
</table>
</div>
<br>
<br>
<br>
<a onclick="text2.style.display='none';an.style.display='block2';zu.style.display='none'" id="zu" style="display: block2" href="#neu2"><img src="img/X.jpg" /></a>
<a onclick="text2.style.display='block2';an.style.display='none';zu.style.display='block2'" id="an" style="display: none" href="#neu2"></a>
<a name="neu2"></a><DIV id="text2" style="display: block2">
<h4>In den letzten f&uumlnf Tagen wurden in Ihren Gruppen diese Nachrichten gepostet:</h4>

<table width="80%">
  <tr>
    <th width="15%">Gruppe</th>
    <th width="15%">Absender</th>
    <th width="15%">Datum</th>
    <th>Nachricht</th>
  </tr>
  
  <?php foreach ($aktnachricht as $zaehler => $nachricht) {?>
  
  <tr>
    <td><?=$nachricht->getGruppe()->getGruppenname()?></td>
    <td><?=$nachricht->getUser()->getUsername()?></td>
    <td><?=$nachricht->getdatum()?> 
    <td><?=$nachricht->getText()?></td>
  </tr>
  <?php }?>
</table>
</div>

	
<?php }
?>