 <h1>Overview</span></h1>
 
<?php
	session_start();
	if($_SESSION['angemeldet'] == 'ja'){
		echo $_REQUEST['message'];
	?>

<div class=>Hallo <?=$user[0]->getVorname();?>! Sie wurden erfolgreich eingeloggt.</div>
<br>
<br>
<h4>In den letzten f&uumlnf Tagen wurden in Ihren Gruppen folgende Zahlungen erstellt:</h4>

<table>
  <tr>
    <th width="80">Gruppe</th>
    <th width="80">Zahlungsbeschreibung</th>
    <th width="80">Zahlungsdatum</th>
    <th width="80">Betrag</th>
    <th width="80">Kategorie</th>
    <th width="80">Erstellungsdatum</th>
  </tr>
  
	<?php foreach ($aktzahlung as $zaehler => $zahlung) {?>

  <tr>
    <td align="center"><?=$zahlung->getGruppe()->getGruppenname()?></td>
    <td align="center"><?=$zahlung->getZahlungsbeschreibung()?></td>
    <td align="center"><?=$zahlung->getZahlungsdatum()?></td>
    <td align="center"><?=$zahlung->getBetrag()?></td>
    <td align="center"><?=$zahlung->getKategorie()->getKategoriebeschreibung()?></td>
    <td align="center"><?=$zahlung->getErstellungsdatum()?></td>
  </tr>
  <?php }?>
</table>
<br>
<br>
<br>
<h4>In den letzten f&uumlnf Tagen wurden in Ihren Gruppen diese Nachrichten gepostet:</h4>

<table>
  <tr>
    <th>Gruppe</th>
    <th>Absender</th>
    <th>Datum</th>
    <th>Nachricht</th>
  </tr>
  
  <?php foreach ($aktnachricht as $zaehler => $nachricht) {?>
  
  <tr>
    <td><?=$nachricht->getGruppe()->getGruppenname()?></td>
    <td><?=$nachricht->getUser()->getUsername()?></td>
    <td><?=$nachricht->getdatum()?> 
    <td><?=$nachricht->getText()?></td>
  </tr>
  <?php }?>
</table>


	
<?php }
?>