<head>
  <meta charset="UTF-8">

  <!--weitere Angaben für den head-->

  <script type="text/javascript" src="js/TableSort.js"></script>
 </head>


<?=$msg?>

<legend><h1>Gruppenverlauf</h1></legend>

<div class=>
<table>
<tr><td>Gruppenname: <?=$gruppe[0]->getGruppenname()?></td><td rowspan=2 width="300" align="right"><img src =<?=$gruppe[0]->getGruppenbildpfad()?> class="big-circular-image" height = "100" width = "100" alt = "Kein Bild vorhanden"></td></tr>
<tr><td>Beschreibung: <?=$gruppe[0]->getGruppenbeschreibung()?></td></tr>
</table>
</div>
<div class=>
<table>
</table>
</div>

<br><br>


<table class="datentabelle sortierbar">
<thead>
<tr class="datentabelle">
	<th class="datentabelle sortierbar">Zeitpunkt</th>
	<th class="datentabelle">Beschreibung</th>
</tr>
</thead>

<tbody>
<?php
foreach($ereignisListe as $zaehler => $ereignis) {
?>

<tr class="datentabelle">
	<td class="datentabelle"><?=$ereignis->getZeitpunkt()?></td>
	<td class="datentabelle"><?=$ereignis->getBeschreibung()?></td>
</tr>

<?php 
}
?>
</tbody>
</table>

