<?=$msg?>

<h1>GRUPPENVERLAUF</h1>

<div class=>
<table>
<tr><td>Gruppenname: <?=$gruppe[0]->getGruppenname()?></td><td rowspan=2 width="300" align="right"><img src =<?=$gruppe[0]->getGruppenbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></td></tr>
<tr><td>Beschreibung: <?=$gruppe[0]->getGruppenbeschreibung()?></td></tr>
</table>
</div>
<div class=>
<table>
</table>
</div>

<br><br>


<table><tr><th>Zeitpunkt</th><th>Beschreibung</th></tr>
<?php
foreach($ereignisListe as $zaehler => $ereignis){

$session_start();
echo $_SESSION['user']->getUsername();

?>

<tr><td><?=$ereignis->getZeitpunkt()?></td><td><?=$ereignis->getBeschreibung()?></td></tr>

<?php 
}
?>
</table>

