<?=$msg?>

<h1>GRUPPENVERLAUF</h1>

<div class=>
<table>
<tr><td>Gruppenname: <?=$gruppe[0]->getGruppenname()?></td><td rowspan=2 width="300" align="right"><img src =<?=$gruppe[0]->getGruppenbildpfad()?> height = "100" width = "100" alt = "Kein Bild vorhanden"></td></tr>
<tr><td>Beschreibung: <?=$gruppe[0]->getGruppenbeschreibung()?></td></tr>
</table>
</div>




<table>
	<tr><th>Gruppenmitglieder:</th></tr>
	<tr>
		<th></th>
		<th>Vorname</th>
		<th>Nachname</th>
		<th>Benutzername</th>
		<th>Gruppenadmin</th>
		<th></th>
	</tr>
	
	
	
	<br>
	<br>
	<form action="usersuchen" method="post">

	<table>
		<th>Neues Mitglied hinzuf&uuml;gen</th>
		<tr><td>Suche:</td><td><input name="suche" type="text" maxlength="255" size="20" required></td>
		 <input type="hidden" name="g_id" readonly="readonly" value="<?=$gruppe[0]->getG_id()?>">
		<td><input type="submit" value="User suchen"></td> </tr>
	</table>
	</form>
	
	
	
	

