<?php session_start();?>
<?=$msg?>
<?=$err?>
<h1>Zahlung erstellen</h1>
<br>
<form action="zahlunganlegen" method="post">

<table>
<tr><td>Zahlungsbeschreibung: </td>
<td><input class="form-control" name="zahlungsbeschreibung" type="text" maxlength="50" size="20" value="<?=$zahlung[0]->getZahlungsbeschreibung()?>" required>
</td></tr>

<tr><td>Betrag: </td>
<td><input class="form-control" name="betrag" type="text" maxlength="50" size="20"  value="<?=$zahlung[0]->getBetrag()?>" required>
</td></tr>

<tr><td>Zahlungsdatum: </td>
<td><input class="form-control" type="date" name="zahlungsdatum" value="<?=$erstellungsdatum?>" placeholder="YYYY-MM-DD" required>
</td></tr>

<tr>
	<td>Kategorie:</td><td>
			<select name='kategorie'>
				<?php 
				foreach ($kategorieListe as $counter => $kategorie) {
					if ($kategorie->getKategoriebeschreibung()=="Keine Kategorie") {
						?>
						<option selected value='<?=$kategorie->getK_id()?>'>
						<?=$kategorie->getKategoriebeschreibung()?>
						</option>						
			<?php	} else {
				?>
					<option value='<?=$kategorie->getK_id()?>'
						<?php // Die ausgewählte Kategorie wird wieder mitgeladen
									if ($kategorie->getK_id() == $k_id)
										echo "selected='selected'";
							?>
					>
						<?=$kategorie->getKategoriebeschreibung()?>
					</option>
				<?php 
					}
				}
				?>
			</select></td>
</tr>

<!--  Oben die alternative Kategorieliste
<tr><td>Kategorie: </td><td>
	<select name="kategorie" size="5">
	<?php
	//Alle Kategorien in die Auswahlliste schreiben
	//foreach ($kategorieListe as $zaehler => $kategorie) { ?>
			<option selected value='<?php //=$kategorie->getK_id()?>'> <?php //=$kategorie->getKategoriebeschreibung() ?> </option>
	<?php // } ?> 
	</select>
</td></tr> 
-->

<tr>
<td>Teilnehmer: </td><td>

	<fieldset>
		<?php 
		//Alle Gruppenmitglieder in die Auswahlliste schreiben
		foreach ($mitgliederListe as $zaehler => $mitglied) { ?>	
			<input type="hidden" name="zahlungsteilnehmer[]" value='<?=$mitglied->getU_id()?>'>
			<?=$mitglied->getUsername()?>	
			<br>Anteil: <input type="text" name="anteilsbetrag[]" placeholder="Euro.Cent">
			<br>	 	 			
		<?php 
		} ?> 
	</fieldset></td>
</tr>


<tr><td>										
<input type="hidden" name="g_id" value='<?=$gruppe[0]->getG_id()?>'>																		
<input class="button" type="submit" name="speichern" value="Zahlung anlegen">
</td></tr>
</table>
	</form>
