<?=$msg?>
<h3>Die Suche ergab folgende Ergebnisse:</h3>
<br><br>
<center>
<table border="0" width="100%">
<tr>
<th> User-ID 		</th>
<th> Benutzername 	</th>
<th> Vorname 		</th>
<th> Nachname 		</th>
<th> Passwort		</th>
<th> E-Mail			</th>
<th> Deaktiviert 	</th>
<th> Systemadmin 	</th>
<th> 				</th>
<th> 				</th>


</tr>
<?php 
	foreach ($suchuserListe as $zaehler => $user) {
	?>
<tr>
			<td height="45">	<?=$user->getU_id()?>			</td>
			<td>	<?=$user->getUsername()?>		</td>
			<td>	<?=$user->getVorname()?>		</td>
			<td>	<?=$user->getNachname()?>		</td>
			<td>	<?=$user->getPasswort()?>		</td>
			<td>	<?=$user->getEmail()?>			</td>
			<td>	<?=$user->getDeaktiviert()?>	</td>
			<td>	<?=$user->getSystemadmin()?>	</td> 
			
			<?php if($user->getDeaktiviert() == 0){ ?>
			<td>	<button><a href=benutzerdeaktivieren?u_id=<?=$user->getU_id()?>>Benutzer deaktivieren</a></button>
			<?php } 
			else{ ?>
			<td>	<button><a href=benutzerreaktivieren?u_id=<?=$user->getU_id()?>>Benutzer reaktivieren</a></button>

<?php
			}
	}
?>

</tr>
</table>

</center>