<h1>Login</h1>
<br><br>

<div class="container">

<form method='post'>

<table>

<tr><td>E-Mail:</td><td> <input type="email" name="email" required></td></tr>
<tr><td>Passwort:</td><td> <input type="password" name="pwd" required></td></tr>

</table>
<a href = "http://132.231.36.206/emailpasswort" > Passwort vergessen? </a>

<br><br>

<input type="submit" name="loginfunc" value="Login">

</form>
</div>

