<h1>Login</h1>
<br><br>

<div class="container">

<form method='post'>

<table>
<input type="email" value="<?=isset($email) ? $email : ""?>" placeholder="E-Mail"
onfocus="if(this.value=='')
this.value='';" onblur="if(this.value=='')
this.value='' placeholder="E-Mail";" > 

<tr><td>E-Mail:</td><td>
<input type="email" value="<?=isset($email) ? $email : ""?>" placeholder="E-Mail"
onfocus="if(this.value=='')
this.value='';" onblur="if(this.value=='') {
this.value='' placeholder="E-Mail" required;"> 

 <input type="email" name="email" value="<?=isset($email) ? $email : ""?>" placeholder="E-Mail" required></td></tr>
<tr><td>Passwort:</td><td> <input type="password" name="pwd" placeholder="Passwort" required></td></tr>

</table>

<br>

<a href = "http://132.231.36.206/emailpasswort"> Passwort vergessen? </a>

<br><br>

<input type="submit" name="loginfunc" value="Login">

</form>
</div>

