<?=$msg?>

<h1>Login</h1>
<br>
<br>


 <form>
  <div class="form-group">
    <label for="email">E-Mail:</label>
    <input type="email" class="form-control" id="email" name="email" value="<?=isset($email) ? $email : ""?>" placeholder="E-Mail" required>
  </div>
  <div class="form-group">
    <label for="pwd">Passwort:</label>
    <input type="password" class="form-control" id="pwd" placeholder="Passwort" required>
  </div>
  <div class="checkbox">
    <label><a href = "http://132.231.36.206/emailpasswort"> Passwort vergessen?</a></label>
  </div>
  <button type="submit" class="button" name="loginfunc" value="Login">Login</button>
</form>




<div class="container">

<form method='post' action='login'>
<table>
<tr><td>E-Mail:</td><td><input type="email" name="email" value="<?=isset($email) ? $email : ""?>" placeholder="E-Mail" required></td></tr>
<tr><td>Passwort:</td><td> <input type="password" name="pwd" placeholder="Passwort" required></td></tr>
</table>

<br>

<a href = "http://132.231.36.206/emailpasswort"> Passwort vergessen? </a>
<br>
<input class="button" type="submit" name="loginfunc" value="Login">

</form>
</div>

