<h1>Kategorien</h1>
<center>
<table border = 1>
<tr>

<th> Kategorie-ID	</th>
<th> Kategoriebeschreibung 	</th>
<th> 				</th>
<th> 				</th>

</tr>
<?php 
	foreach ($kategorieListe as $zaehler => $kategorie) {
	?>
<tr>
			<td>	<?=$kategorie->getK_id()?>						</td>
			<td>	<?=$kategorie->getKategoriebeschreibung()?>		</td>
			
			<th><a href='gruppeanlegen'>Neue Gruppe anlegen</a></th>
		
		

<?php
}	
?>
</tr>
</table>

</center>