<?=$msg?>
<h1>Kategorien</h1>
<center>
<table width="50%" border = 0>
<tr>

<th> Kategorie-ID	</th>
<th> Kategoriebeschreibung 	</th>

</tr>
<?php 
	foreach ($kategorieListe as $zaehler => $kategorie) {
	?>
<tr>
			<td>	<?=$kategorie->getK_id()?>															</td>
			<td>	<?=$kategorie->getKategoriebeschreibung()?>											</td>
			<td> 	<a href='kategorieedit?k_id=<?=$kategorie->getK_id()?>'><img src="img/edit.jpg" /></a> 	</td>
</tr>


<?php
}	
?>
<tr><td> </td></tr>
<tr>
<th> <a href='kategorieanlegen'>Neue Kategorie hinzuf&uumlgen</a> </th>
</tr>
		
</tr>
</table>

</center>