<?= $this->doctype() ?>

<?php session_start(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('GroupPay')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/gp.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                    
                    	<?php if ($_SESSION['angemeldet']=='ja'){?> 
								<li class="active"><a href="<?= $this->url('overview') ?>">Overview</a></li>
								<li class="active"><a href="<?= $this->url('groupoverview') ?>">Meine Gruppen</a></li>	
								<?php } else if($_SESSION['systemadmin']=="ja") {?>
								<li class="active"><a href="<?= $this->url('adminoverview') ?>">Adminstartseite</a></li>	
								<li class="active"><a href="<?= $this->url('benutzertabelle') ?>">Benutzertabelle</a></li>	
								<li class="active"><a href="<?= $this->url('kategorien') ?>">Kategorien</a></li>
								

						<?php } else {?>
								<li class="active"><a href="<?= $this->url('application') ?>">Startseite</a></li>
								<li class="active"><a href="<?= $this->url('help') ?>">Hilfe</a></li>
						<?php }?>
						
                        
                        
                        
                        
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                     	        				<!--  	<li><a href="http://132.231.36.206/"><span class=></span> Registrieren</a></li>
        				      				 		<li><a href="http://132.231.36.206/login"><span ></span> Login</a></li> -->
       
										
										<?php if ($_SESSION['angemeldet']=='ja' || $_SESSION['systemadmin']=="ja"){?> 
											<li><a href="http://132.231.36.206.ml/"><span class=></span>Logout</a></li>
										<?php } else {?>
											<li><a href="http://132.231.36.206/login"><span class=></span>Login</a></li>
											<li><a href="http://132.231.36.206/registrieren"><span class=></span> Registrieren</a></li>
										<?php }?>
      				</ul>
      				 	      			
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
