<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('GroupPay')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/gp.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="active"><a href="<?= $this->url('overview') ?>">Overview</a></li>
                        <li class="active"><a href="<?= $this->url('help') ?>">Help</a></li>
                        <li class="active"><a href="<?= $this->url('gruppeanlegen') ?>">GruppenController</a></li>
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                     	        					<li><a href="http://132.231.36.206/"><span class=></span> Registrieren</a></li>
        				      				 	<li><a href="http://132.231.36.206/anmelden"><span ></span> Login</a></li>
       
										<!--  So verwenden, wenn die Actions funktionieren
										if ($user->isLogedIn()) {
											<li><a href="http://132.231.36.206/logout"><span class=></span>Logout</a></li>";
										} else {
											<li><a href="http://132.231.36.206/anmelden"><span class=></span>Login</a></li>";
											<li><a href="http://132.231.36.206/registrieren"><span class=></span> Registrieren</a></li>
			}
      				 	      				</ul>
      				 	      			-->
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
