<?php session_start();?>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<h1>Neue Gruppe anlegen</h1>

<?php if (isset($errors)) {
	foreach ($errors as $err) {
		echo "Fehler: " . $err . "<br>";
	}
}?>

<form enctype="multipart/form-data" action="gruppeanlegen" method="POST">	
	<table class="form-group">
		<tr class="form-group"><td class="form-group">Gruppenname</td><td><input class="form-group" type="text" name="gruppenname" required value="<?=$gruppe[0]->getGruppenname()?>" ></td></tr>
		<tr class="form-group"><td class="form-group">Beschreibung</td><td><input class="form-group" type="text" name="gruppenbeschreibung" value="<?=$gruppe[0]->getGruppenbeschreibung()  ?>" ></td></tr>
	</table>

	<input type="hidden" name="g_id" readonly="readonly" value="<?=!is_null ($gruppe[0]->getG_id()) ? $gruppe[0]->getG_id():"<automatisch>"?>">

    
       <!-- <input type="hidden" name="MAX_FILE_SIZE" value="100000" /> -->
	<table>
       	<tr><td>Gruppenbild ausw&auml;hlen:</td></tr>
	</table>
	<input type="file" name="uploadedfile" />
    <input type="hidden" name="g_id" readonly="readonly" value="<?=!is_null ($gruppe[0]->getG_id()) ? $gruppe[0]->getG_id():"<automatisch>"?>">
    <br />
    <input class="button" type="submit" name="speichern" value="Gruppe anlegen">
</form>  
         