<?php session_start();?>

<h1>Neue Kategorie anlegen</h1>

<?php if (isset($errors)) {
	foreach ($errors as $err) {
		echo "Fehler: " . $err . "<br>";
	}
}?>

<?=$keineeingabenachricht?>

<form method="POST">	
	<table>
		<tr><td>Kategoriename</td><td><input type="text" name="kategoriebeschreibung" required value="<?=$kategorie[0]->getKategoriebeschreibung()?>" ></td></tr>
		
	</table>

	<input type="hidden" name="k_id" readonly="readonly" value="<?=!is_null ($kategorie[0]->getK_id()) ? $Kategorie[0]->getK_id():"<automatisch>"?>">
	
	<input class="button" type="submit" name="speichern" value="Kategorie anlegen">
</form>

  