<head>
<style>
.button{
    font-size: 1.5rem;
}
</style>
</head>

<form method='post'>

<div>Willst die Einladung in die Gruppe '<?=$gruppe[0]->getGruppenname()?>' annehmen,<?=$user[0]->getVorname()?> ?</div>
	
	<input type='hidden' name='u_id' value='<?=$user[0]->getU_id()?>'>
		
	<input class='button' type='submit' name='speichern' value='Ja'>
	<input class='button' type='submit' name='abbrechen' value='Nein'>
		
</form>
