<div class="container">
<form method='post' action='login'>
<label><b>Benutzername</b></label>
<input type="text" placeholder="Benutzername eingeben" name="uname" required>
<br>
<label><b>Passwort</b></label>
<input type="password" placeholder="Passwort eingeben" name="pwd" required>

<button type="submit">  Login</button>
<input type="checkbox" checked="checked"> Remember me
</form>
</div>
