<div class="container">
<form method='post' action='login'>
<table>
<tr><td><label><b>Benutzername</b></label></td>
<td><input type="text" placeholder="Benutzername eingeben" name="uname" required></td></tr>
<br>
<tr><td><label><b>Passwort</b></label></td>
<td><input type="password" placeholder="Passwort eingeben" name="pwd" required></td></tr>
<br><br>
<tr><td><button type="submit">  Login</button>
<input type="checkbox" checked="checked"> Remember me</td></tr>
</table>
</form>
</div>
