<?=$msg?>


<h1><?=$zahlung[0]->getZahlungsbeschreibung()?></h1>

<div class=>
<table>
<tr><td>Betrag: <?=$zahlung[0]->getBetrag()?></td>
<tr><td>Zahlungsdatum: <?=$zahlung[0]->getZahlungsdatum()?></td></tr>
<tr><td>Kategorie: <?=$zahlung[0]->getKategorie()->getKategoriebeschreibung()?></td></tr>
<tr><td>Gruppe: <?=$zahlung[0]->getGruppe()->getGruppenname()?></td></tr>
<tr><td>Zahlungsteilnehmer:</td></tr>
</table>
</div>



<form action="zahlungbearbeiten" method="post">
<table>
<th>Bearbeiten dieser Zahlung</th></tr>
<td><input type="hidden" name='u_id' value=<?=$_REQUEST['g_id']?></td> </tr>
<td><input type="submit" value="Zahlung bearbeiten"></td> </tr>
</table>
</form>	
