<?php session_start();?>

<h1>Gruppendetails bearbeiten</h1>

<?php if (isset($errors)) {
	foreach ($errors as $err) {
		echo "Fehler: " . $err . "<br>";
	}
}?>

    <form enctype="multipart/form-data" action="groupedit" method="POST">
	<table>
		<tr><td>Gruppenname</td><td><input type="text" name="gruppenname" required value="<?=$gruppe[0]->getGruppenname()?>" readonly></td></tr>
		<tr><td>Beschreibung</td><td><input type="text" name="gruppenbeschreibung" value="<?=$gruppe[0]->getGruppenbeschreibung()  ?>" ></td></tr>
		
	</table>

	<input type="hidden" name="gruppenbildpfad" reaonly="readonly" value="<?=$gruppe[0]->getGruppenbildpfad()?>">

<br>
      
        <!--  <input type="hidden" name="MAX_FILE_SIZE" value="100000" /> -->
        	<table>
        	<tr><td>Gruppenbild ausw&auml;hlen:</td></tr>
        	<tr><td><img src =<?=$gruppe[0]->getGruppenbildpfad()?> height = "50" width = "50" alt = "Kein Bild vorhanden"></td></tr>
        	</table>
        <input type="file" name="uploadedfile" />
        <input type="hidden" name="g_id" readonly="readonly" value="<?=!is_null ($gruppe[0]->getG_id()) ? $gruppe[0]->getG_id():"<automatisch>"?>">
        <br />
        <input class="button" type="submit" name="speichern" value="Speichern">
    </form>