<?php session_start();?>

<h1>Gruppendetails bearbeiten</h1>

<?php if (isset($errors)) {
	foreach ($errors as $err) {
		echo "Fehler: " . $err . "<br>";
	}
}?>

<form method="POST">	
	<table>
		<tr><td>Gruppenname</td><td><input type="text" name="gruppenname" required value="<?=$gruppe[0]->getGruppenname()?>" ></td></tr>
		<tr><td>Beschreibung</td><td><input type="text" name="gruppenbeschreibung" value="<?=$gruppe[0]->getGruppenbeschreibung()  ?>" ></td></tr>
		<tr><td>Gruppenbildpfad </td><td><input type="text" name="gruppenbildpfad" value="<?=$gruppe[0]->getGruppenbildpfad()?>"></td></tr>
	</table>

	<input type="hidden" name="g_id" readonly="readonly" value="<?=!is_null ($gruppe[0]->getG_id()) ? $gruppe[0]->getG_id():"<automatisch>"?>">
	
	<input type="submit" name="speichern" value="Speichern">
</form>

    
    
    <form enctype="multipart/form-data" action="file" method="POST">
        <!--  <input type="hidden" name="MAX_FILE_SIZE" value="100000" /> -->
            Choose a file to upload: <input name="uploadedfile" type="file" />
        <br />
        <input type="submit" name="upload" value="Upload File" />
    </form>