<?=$msg?>

<h1>Neue Mitglieder hinzuf&auml;gen zu der Gruppe <?=$gruppe[0]->getGruppenname()?>:</h1>
<center>

<form action="usersuchen" method="post">


<table>
	<tr><td>Suche:</td><td><input name="suche" type="text" maxlength="255" size="20" required></td>
	<input type="hidden" name="g_id" readonly="readonly" value="<?=$gruppe[0]->getG_id()?>">
	<td><input type="submit" value="User suchen"></td> </tr> 
</table>
</form>
<br>

<table border = 1>
<tr>

<th> Benutzername 	</th>
<th> Vorname 		</th>
<th> Nachname 		</th>
<th> E-Mail			</th>
<th> Deaktiviert 	</th>
<th> 				</th>
<th> 				</th>

</tr>
<?php 
	foreach ($suchuserListe as $zaehler => $user) {
	?>
<tr>
			<td>	<?=$user->getUsername()?>		</td>
			<td>	<?=$user->getVorname()?>		</td>
			<td>	<?=$user->getNachname()?>		</td>
			<td>	<?=$user->getEmail()?>			</td>
			<td>	<?=$user->getDeaktiviert()?>	</td>
			
			<?php if($user->getDeaktiviert() == 0){ ?>
			<td>	<a href=benutzerdeaktivieren?u_id=<?=$user->getU_id()?>>Benutzer deaktivieren</a>
			<?php } 
			else{ ?>
			<td>	<a href=benutzerreaktivieren?u_id=<?=$user->getU_id()?>>Benutzer reaktivieren</a>

<?php
			}
	}
?>
</tr>
</table>

</center>