<?=$msg?>

 <meta charset="UTF-8"> 


<legend><h1>Neue Mitglieder zu der Gruppe <?=$gruppe[0]->getGruppenname()?> hinzuf&uuml;gen:</h1></legend>
<center>

<!-- alte Suche kann aufgrund intelligenter Suche weg
<form action="usersuchen" method="post">

<table >
	<tr><td>Suche:</td><td><input name="suche" type="text" value="<?=$suche?>" maxlength="255" size="20" required></td>
	<input type="hidden" name="g_id" readonly="readonly" value="<?=$gruppe[0]->getG_id()?>">
	<td><input class="button" type="submit" value="User suchen"></td> </tr> 
</table>
</form>
<br>
 -->
<div class="form-group" style="width:300px"><label>Suche: </label><input class="form-control" type="text" placeholder="Search..." id="search_field" oninput="myTable.style.visibility=(search_field.value.length<1)?'hidden':'visible';"></div>
<br>


<table class="datentabelle" id="myTable" style="visibility:hidden; border:0; width:80%">

<tr class="datentabelle" id="myHead">

<th class="datentabelle"> Benutzername 	</th>
<th class="datentabelle"> Vorname 		</th>
<th class="datentabelle"> Nachname 		</th>
<th class="datentabelle"> E-Mail		</th>
<th class="datentabelle"> Einladen		</th>

</tr>
<?php 
	foreach ($suchuserListe as $zaehler => $user) {
	?>
<tr class="datentabelle">
			<td class="datentabelle">	<?=$user->getUsername()?>		</td>
			<td class="datentabelle">	<?=$user->getVorname()?>		</td>
			<td class="datentabelle">	<?=$user->getNachname()?>		</td>
			<td class="datentabelle">	<?=$user->getEmail()?>			</td>
		<td class="datentabelle"><a href='usersuchen?g_id=<?=$gruppe[0]->getG_id()?>&u_id=<?=$user->getU_id()?>&einladen=einladen'><img src="img/add2.jpg" style="margin: auto; display:block" title="Einladen"/></a></td>
<?php
			
	}
?>
</tr>
</table>

</center>

<script src="https://code.jquery.com/jquery.min.js"></script>

<script type="text/javascript">

$('#search_field').on('keyup', function() {
	  var value = $(this).val();
	  var patt = new RegExp(value, "i");

	  $('#myTable').find('tr').each(function() {
	    if (!($(this).find('td').text().search(patt) >= 0)) {
	      $(this).not('#myHead').hide();
	    }
	    if (($(this).find('td').text().search(patt) >= 0)) {
	      $(this).show();
	    }
	  });

	});

</script>