<?$msg?>
<h1>Passwort zur&uumlcksetzen</h1>
<br><br>

<div class="container">

<form method='post'>

<div class="form-group" style="width:300px">
<label>Altes Passwort:</label>
<input class="form-control" type="password" name="altespasswort" required>
</div>

<div class="form-group" style="width:300px">
<label>Neues Passwort:</label> 
<input class="form-control" type="password" name="passwort" required>
</div>

<div class="form-group" style="width:300px">
<label>Neues Passwort wiederholen:</label>
<input class="form-control" type="password" name="passwortwdh" required>
</div>

<br><br>

<input class="button" type="submit" name="passwordreset" value="Passwort zur&uuml;cksetzen">
<br><br>
<div>(Beachte: Du kannst dein Passwort nur einmal pro Sitzung zur&uuml;cksetzen!)</div>
</form>
</div>
