<h1>Passwort vergessen</h1>
<br><br>

<div class="container">

<form method='post'>

<table>
<tr><td>Altes Passwort:</td><td> <input type="password" name="altespasswort" required></td></tr>
<tr><td>Neues Passwort:</td><td> <input type="password" name="passwort" required></td></tr>
<tr><td>Neues Passwort wiederholen:</td><td> <input type="password" name="passwortwdh" required></td></tr>

</table>

<br><br>

<input type="submit" name="passwordreset" value="Passwort zur&uuml;cksetzen">

</form>
</div>
