 <?php session_start();
use Application\Model\Zahlungsteilnehmer;?>
<?=$msg?>
<?=$err?>
<form action="statistiken" method="post">

<tr><td>Kategorie: </td><td>
	<select name="kategorie" size="5">
	<?php
	//Alle Kategorien in die Auswahlliste schreiben
	foreach ($kategorieliste as $zaehler => $kategorie) { ?>
			<option value='<?=$kategorie->getK_id()?>'> <?=$kategorie->getKategoriebeschreibung() ?> </option>
	<?php } ?> 
	</select>
</td>
<td>nach: </td><td><input type="date" name="afterdate" value="<?=$datum?>" placeholder="YYYY-MM-DD">
<td>vor: </td><td><input type="date" name="beforedate" value="<?=$datum?>" placeholder="YYYY-MM-DD"><td>
</td>


<td>status: <fieldset>
			<label>
			<input type="checkbox" name="status[]" value='offen'>
			</input>
			</label>	 	
	</fieldset></td>
	<td>offen <fieldset>
			<label>
			<input type="checkbox" name="status[]" value='geschlossen'>
			</input>
			</label>	 	
	</fieldset></td>
	<td>geschlossen <fieldset>
			<label>
			<input type="checkbox" name="status[]" value='ersteller'>
			</input>
			</label>	 	
	</fieldset></td>
<td>ersteller</td>

</tr>

<p></p>
		<table>
		<td><input type="submit" name="filteranwenden" value="Filtern"></td> </tr>
		</table>
	</form>	


<table>

	<tr>
		<th>Zahlungsbeschreibung  </th>
		<th>Zahlungsdatum </th>
		<th>Betrag </th>
		<th>Kategorie </th>
		<th>Status </th>
		<th>Gruppenname</th>
		<th></th>
	</tr>

<?php 
	foreach ($zahlungenliste as $zaehler => $zahlungsteilnehmer) {
		
	?>

		<tr>
			<td><?=$zahlungsteilnehmer->getZahlung()->getZahlungsbeschreibung()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getZahlungsdatum()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getBetrag()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getKategorie()->getKategoriebeschreibung()?></td> 
			<td><?=$zahlungsteilnehmer->getStatus()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getGruppe()->getGruppenbeschreibung()?></td>
			<td><a href='zahlunganzeigen?z_id=<?=$zahlungsteilnehmer->getZahlung()->getZ_id()?>'><img src="img/show.jpg" /></a>
		</tr>

	<?php 
		
	}
	?>
</table>

