 <?php session_start();
use Application\Model\Zahlungsteilnehmer;?>
<?=$msg?>
<?=$err?>
<tr><td>Kategorie: </td><td>
	<select name="kategorie" size="5">
	<?php
	//Alle Kategorien in die Auswahlliste schreiben
	foreach ($kategorieliste as $zaehler => $kategorie) { ?>
			<option value='<?=$kategorie->getKategoriebeschreibung() ?> </option>
	<?php } ?> 
	</select>
</td></tr>
<p></p>
<form  method="post">
		<table>
		<td><input type="submit" value="Filtern"></td> </tr>
		</table>
	</form>	

<table>

	<tr>
		<th>Zahlungsbeschreibung  </th>
		<th>Zahlungsdatum </th>
		<th>Betrag </th>
		<th>Kategorie </th>
		<th>Status </th>
		<th>Gruppenname</th>
		<th></th>
	</tr>

<?php 
	foreach ($zahlungenliste as $zaehler => $zahlungsteilnehmer) {
		
	?>

		<tr>
			<td><?=$zahlungsteilnehmer->getZahlung()->getZahlungsbeschreibung()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getZahlungsdatum()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getBetrag()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getKategorie()->getKategoriebeschreibung()?></td> 
			<td><?=$zahlungsteilnehmer->getStatus()?></td>
			<td><?=$zahlungsteilnehmer->getZahlung()->getGruppe()->getGruppenbeschreibung()?></td>
			<td><a href='zahlunganzeigen?z_id=<?=$zahlungsteilnehmer->getZahlung()->getZ_id()?>'><img src="img/show.jpg" /></a>
		</tr>

	<?php 
		
	}
	?>

