 <h1>Statistiken</span></h1>
 <?php session_start();
use Application\Model\Zahlungsteilnehmer;?>
<?=$msg?>
<?=$err?>

<table>

	<tr>
		<th>Zahlungsbeschreibung  </th>
		<th>Zahlungsdatum </th>
		<th>Betrag </th>
		<th>Kategorie </th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

<?php 
	foreach ($zahlungenliste as $zaehler => $zahlung) {
		
	?>

		<tr>
			<td><?=$zahlung->getZ_id()?></td>
			<td><?=$zahlung->getZahlungsbeschreibung()?></td>
			<td><?=$zahlung->getBetrag()?></td>
			<td><?=$zahlung->getK_id()?></td>
			
			<td><a href='groupshow?g_id=<?=$gruppe->getG_id()?>'><img src="img/show.jpg" /></a>
			<?php //Nicht schön programmiert
			foreach ($gruppenadminListe as $counter => $gruppenmitglied) { 
				
				if ($gruppenmitglied->getG_id()==$gruppe->getG_id() && $gruppenmitglied->getU_id()==$u_id && $gruppenmitglied->getGruppenadmin()==1) { ?>
					<a href='groupedit?g_id=<?=$gruppe->getG_id()?>'><img src="img/edit.jpg" /></a>
					<a href='groupdelete?g_id=<?=$gruppe->getG_id()?>'><img src="img/delete.png" /></a>
				<?php }
				
				}
			?>
			</td>
		</tr>

	<?php 
		
	}
	?>

