<?php 
session_start();
session_destroy(); 
?>


<body style="background-image: url('img/marienkaefer.jpg')">
 
<?=$msg?>
<?=$err?>
 
 
<h1>Herzlich Willkommen bei GroupPay! </h1>
<br>

<!-- GroupPay Logo -->
<div class="image-wrapper" align="center" >
<img src = "img/grouppaylogo.png"  alt= "GroupPay" style="width:80%; height:10%">
</div> 
<!-- Hier steht die Beschreibung der Website laut Pflichtenheft (F101) -->


<h4>
GroupPay ist ein Zahlungsportal für Gruppen. 
Die jeweiligen Gruppen sollen eine Übersicht über die getätigten Zahlungen innerhalb der Gruppe erhalten, wobei festgestellt werden kann, wer an diesen beteiligt ist 
Dabei können die Zahlungen auf die einzelnen Personen entsprechend ihrer Anteile aufgeteilt werden.
Daraus ergibt sich die Möglichkeit, festzustellen, welche Beträge anderen gegenüber noch offen sind.
</h4>
<br><br>        
          
<i>
Beispiel:
<br> 
Anton, Beate und Charlie leben gemeinsam in einer Wohngemeinschaft.
Anfangs haben die Mitbewohner ausgemacht, dass jeder von ihnen abwechselnd den Einkauf zahlt.Um jedoch auszuschließen, dass einer von ihnen mehr zahlen muss, nutzen sie GroupPay.
Charlie hat daher eine Gruppe WG erstellt und seine beiden Mitbewohner hinzugefügt.
Für den ersten Einkauf zahlt Anton 60€, die er in die Anwendung einträgt und seinen Mitbewohnern je zu einem Drittel anrechnet.

</i> 
</body>         