<h1>Registrierung best&auml;tigen</h1>

<br>

<div class="container">

<form method='post'>

<div class="form-group" style="width:300px">
	<label>E-Mail:</label>
	<input class="form-control" type="email" name="email" required>
</div>

<div class="form-group" style="width:300px">	
	<label>E-Mail wiederholen: </label>
	<input class="form-control" type="email" name="emailwdh" required>
</div>


<input class="button" type="submit" name="confirm" value="Registrierung best&auml;tigen">

</form>
</div>
