<h1>Registrierung best&aumltigen</h1>

<br><br>

<div class="container">

<form method='post'>

<table>

<tr><td>E-Mail:</td><td> <input type="email" name="email" required></td></tr>
<tr><td>E-Mail wiederholen: </td><td> <input type="email" name="emailwdh" required></td></tr>
</table>


<br><br>

<input class="button" type="submit" name="confirm" value="Registrierung best&auml;tigen">

</form>
</div>
