<form action="zahlungbearbeiten" method="post">

<table>
<th>Zahlung begleichen</th>
<tr><td>Zahlungsbeschreibung: </td><td><input name="zahlungsbeschreibung" type="text" maxlength="50" size="20" value="<?=$zahlung[0]->getZahlungsbeschreibung()?>" required readonly></td></tr>
<tr><td>Betrag: </td><td><input name="betrag" type="text" maxlength="50" size="20" value="<?=$zahlung[0]->getBetrag()?>" required readonly></td></tr>
<tr><td>Zahlungsdatum: </td><td><input type="date" name="zahlungsdatum" value="<?=$zahlung[0]->getZahlungsdatum()?>" placeholder="YYYY-MM-DD" required readonly></td></tr>
<tr><td>Kategorie: </td><td>
	<select disabled name="kategorie">
	<?php

	//Alle Kategorien in die Auswahlliste schreiben
	foreach ($kategorieListe as $zaehler => $kategorie) { ?>
			<option value='<?=$kategorie->getK_id()?>' <?php 
									if ($kategorie->getK_id() == $zahlung[0]->getKategorie()->getK_id() )
										echo "selected='selected'";
								?>
			> <?=$kategorie->getKategoriebeschreibung() ?> </option>
	<?php } 

	?> 
	</select>
</td></tr>
<tr><td>Teilnehmer: </td>

	<td><fieldset>
		<?php 
		
		//Alle Gruppenmitglieder in die Auswahlliste schreiben
		foreach ($mitgliederListe as $zaehler => $mitglied) { ?>	
			<label>
			<input type="hidden" name="zahlungsteilnehmer[]" value='<?=$mitglied->getU_id()?>'>
			<?=$mitglied->getUsername()?>
			
			<?php if ($mitglied->getU_id()==$_SESSION['user']->getU_id()) { ?>
				
				<br>Anteil: <input type="text" name="anteilsbetrag[]" 
				<?php foreach ($zahlungsteilnehmerliste as $counter => $teilnehmer) { 
					if ($teilnehmer->getUser()->getU_id()==$mitglied->getU_id()) {?>
						value="<?=$teilnehmer->getAnteil()?>"
						
						
						<br><label>Restbetrag: </label> <input type="text" readonly required value="<?=$teilnehmer->getRestbetrag()?>">
					<?php } ?>
					
					
						
				<?php }?> 				
				placeholder="Euro.Cent" required readonly>
				
				
			<?php } else { ?>				
				<br>Anteil: <input type="text" readonly name="anteilsbetrag[]" 
				<?php foreach ($zahlungsteilnehmerliste as $counter => $teilnehmer) { 
					if ($teilnehmer->getUser()->getU_id()==$mitglied->getU_id()) {?>
						value="<?=$teilnehmer->getAnteil()?>"
					<?php }
					}
				}?> 
			</label><br></input>
			
			

			

		<?php 
		}
		
		?> 
	</fieldset></td>

</tr>


										
<input type="hidden" name="z_id" value='<?=$zahlung[0]->getZ_id()?>'>
<input type="hidden" name="g_id" value='<?=$gruppe[0]->getG_id()?>'>																		
<tr><td><input class="button" type="submit" name="speichern" value="Speichern"></td> </tr>

</table>
</form>
	
	
	
